version: "3.4"

x-common-variables:
  &env-vars
  HOST_DB: mongo1

networks:
  api-net:

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.4
    restart: always
    ports:
      - "27017:27017"
    networks:
      - api-net
    volumes:
      - ../docker/mongo-data-db-std:/data/db
    environment:
      *env-vars