version: "3.5"

services:

  mongodb-secrets:
    container_name: mongo1-db
    image: mongo:4.4.4
    ports:
      - 27017:27017
    environment:
# ROOT-DB -----------------------------------------------------------------
# MONGO-COMPASS-URL: mongodb://root:root@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      MONGO_INITDB_DATABASE_FILE: /run/secrets/root_db_admin
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/root_password
# MONGO_INITDB_ROOT_USERNAME: root_username
# MONGO_INITDB_ROOT_PASSWORD: root_password

# WEB-APP-DB --------------------------------------------------------------
      MONGO_DATABASE: /run/secrets/db_web_app
      MONGO_USERNAME_FILE: /run/secrets/db_username
      MONGO_PASSWORD_FILE: /run/secrets/db_password
# MONGO_DATABASE: parrot
# MONGO_USERNAME: username
# MONGO_PASSWORD: password
    secrets:
      - root_db_admin
      - root_username
      - root_password
      - db_username
      - db_password
      - db_web_app

secrets:
  root_db_admin:
    file: root-db-secrets/root_admin_db.txt
  root_username:
    file: root-db-secrets/root_username.txt
  root_password:
    file: root-db-secrets/root_password.txt
  db_username:
    file: app-db-secrets/username
  db_password:
    file: app-db-secrets/password
  db_web_app:
    file: app-db-secrets/app_db