server:
  port: ${PORT_API}

spring:
  profiles:
# ACTIVE PROFILES:
# 1) Are UNIQUE
#    - Meaning: IT IS ALLOWED "ONLY ONE PROFILE" in all @Configurations
#    - For example:
#      - TEST
#      - DEV
#      - PROD
# 2) WHEN CHANGE HERE:
#    - "MUST" BE CHANGE: DevTransactionManagerConfig
# 3) Change the Active-Profile according the BOOTSTRAP-SCRIPTS-RUN-CONFIGURATION-INTELLIJ
#    active: dev-single-node-rs
#    active: dev-three-nodes-rs
    active: prod-single-node-rs-auth
    group:
      dev-single-node-rs: dev-singlenode-rs-noauth-props, log
      prod-single-node-rs-auth: prod-singlenode-rs-auth-props, log
      dev-three-nodes-rs: dev-threenodes-rs-noauth-props, log