spring:
  devtools:
    remote:
      secret: mysecret
  data:
    mongodb:
      host: ${HOST_DB}
      port: ${PORT_DB}
      authentication-database: ${AUTH_DB}
      database: ${STD_DB}
      username: ${STD_USER}
      password: ${STD_PASS}