server:
  port: ${PORT_API}

spring:
  profiles:
    active: dev-rs
    group:
      dev-rs: dev-singlenode-replicaset-noauth-props, log
      prod-rs: dev-threenodes-replicaset-noauth-props, log
#      prod-rsa: dev-threenodes-replicaset-auth-props, log