spring:
  main:
    banner-mode: console
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        cache: TRACE
        web: DEBUG
        data:
          convert:
            CustomConversions: ERROR
          mongodb:
            core:
              ReactiveMongoTemplates: DEBUG
  pattern:
    console: >
      %clr(%d{yyyy-MM-dd }){magenta}
      %clr(%d{| E |}){blue}
      %clr(%d{ HH:mm:ss}){magenta}
      %clr(>>==>>){cyan}
      %clr(%-6p){red}
      %clr(<==>){cyan}
      %clr(${PID}){red}
      %clr(>--->){cyan}
      %-32clr(%-5.20logger{0}){yellow}
      %clr(:){red}
      %clr(%m){faint}%n