spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

db:
  mongodb:
    replicaset:
      replicaset_name: ${RS_NAME}
      username: ${RS_USERNAME}
      password: ${RS_PASSWORD}
      root_uri: ${RS_ROOT_URI}
      database: ${RS_DB}
      auth_db: ${RS_AUTH}