version: "3.4"

x-common-variables:
  &env-vars
  RS_ROOT_URI: mongodb://mongo1:9042,mongo2:9142,mongo3:9242
  RS_DB: rs-node3
  RS_NAME: docker-rs
  RS_AUTH: admin
  RS_USERNAME: rs-node3
  RS_PASSWORD: rs-node3
  PORT_API: 8080
  PORT_DEBUG: 5005

volumes:
  api_vol:

networks:
  api_net:

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9042
    ports:
      - "9042:9042"
    depends_on:
      - mongo2
    networks:
      - api_net
    volumes:
      - ~/mongors/data1:/data/db

  mongo2:
    container_name: mongo2
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9142
    ports:
      - "9142:9142"
    depends_on:
      - mongo3
    networks:
      - api_net
    volumes:
      - ~/mongors/data2:/data/db

  mongo3:
    container_name: mongo3
    image: mongo:4.4.4
    restart: always
    ports:
      - "9242:9242"
    command: mongod --replSet docker-rs --port 9242
    networks:
      - api_net
    volumes:
      - ~/mongors/data3:/data/db

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api_vol:/data/db
    depends_on:
      - mongo1
    networks:
      - api_net
    environment:
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m