version: "3.4"

#secrets:
#  db_username:
#    file: ../docker/secrets/prod_rs_username
#  db_password:
#    file: ../docker/secrets/prod_rs_password
#  db_admin:
#    file: ../docker/secrets/prod_rs_admin

x-common-variables:
  &env-vars
  PORT_API: 8080
  PORT_DEBUG: 5005
  RS_ROOT_URI: mongo1:9042
#  RS_ROOT_URI: mongo1:9042,mongo2:9142,mongo3:9242
  RS_AUTH: admin
  RS_USERNAME: admin
  RS_PASSWORD: xxxx


volumes:
  api_vol:

networks:
  api_net:

#https://stackoverflow.com/questions/38524150/mongodb-replica-set-with-simple-password-authentication
#I finally found the answer. MongoDB replica set needs both user account and keyfile. Keyfile seems for authentication between servers in the replica set, not for logging in.
services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9042
    ports:
      - "9042:9042"
    networks:
      - api_net
    volumes:
      - ~/mongors/data1:/data/db
    depends_on:
      - mongo2
#    secrets:
#      - db_username
#      - db_password
#      - db_admin
    env_file:
      - ./envs/env_db_parameters.env
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: user
#      MONGO_INITDB_ROOT_PASSWORD: xxxx
#      RS_USERNAME_FILE: /run/secrets/db_username
#      RS_PASSWORD_FILE: /run/secrets/db_password
#      RS_AUTH_FILE: /run/secrets/db_admin

  mongo2:
    container_name: mongo2
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9142
    ports:
      - "9142:9142"
    networks:
      - api_net
    volumes:
      - ~/mongors/data2:/data/db
    depends_on:
      - mongo3

  mongo3:
    container_name: mongo3
    image: mongo:4.4.4
    restart: always
    ports:
      - "9242:9242"
    command: mongod --replSet docker-rs --port 9242
    networks:
      - api_net
    volumes:
      - ~/mongors/data3:/data/db

  replicaset-setup:
    container_name: replicaset-setup
    image: mongo:4.4.4
    restart: on-failure
#    entrypoint: [ "bash", "-c", "sleep 20 && /scripts/setup.sh" ]
    command: bash -c "
      sleep 20 &&
      chmod +x /scripts/setup.sh &&
      scripts/setup.sh"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - api_net
    volumes:
      - ./rs-script/setup.sh:/scripts/setup.sh

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api_vol:/data/db
    networks:
      - api_net
    depends_on:
      - replicaset-setup
#      - mongo1
#    secrets:
#      - db_username
#      - db_password
#      - db_admin
    env_file:
      - ./envs/env_db_parameters.env
    environment:
#      RS_USERNAME_FILE: /run/secrets/db_username
#      RS_PASSWORD_FILE: /run/secrets/db_password
#      RS_AUTH_FILE: /run/secrets/db_admin
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m