version: "3.4"

x-common-variables:
  &env-vars
  PORT_API: 8080
  RS_ROOT_URI: mongodb://mongo1-db:27017
  RS_DB: dev-rs-db
  RS_NAME: devSingleNodeRs

networks:
  api-net:

services:
  mongo1:
    container_name: mongo1-db
    image: mongo:latest
    command: --replSet devSingleNodeRs
    ports:
      - "27017:27017"
    networks:
      - api-net

  replicaset-setup:
    container_name: replicaset-setup
    image: mongo:latest
    command: bash -c "
      sleep 5 &&
      mongo --host mongo1-db --port 27017 --eval \"rs.initiate()\" &&
      sleep 2 &&
      mongo --host mongo1-db --port 27017 --eval \"rs.status()\" &&
      sleep infinity"
    depends_on:
      - mongo1
    networks:
      - api-net

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ../docker/mongo-data-db:/data/db
    depends_on:
      - replicaset-setup
    networks:
      - api-net
    env_file:
      - ../docker/secrets/secrets_dev_replicaset.env
    environment:
      PORT_DEBUG: 5005
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m