version: "3.4"

secrets:
  RS_USER:
    external: true
  RS_PASSWORD:
    external: true

x-common-variables:
  &env-vars
  PORT_API: 8080
  PORT_DEBUG: 5005
  RS_ROOT_URI: mongodb://mongo1:9042,mongo2:9142,mongo3:9242

volumes:
  api_vol:

networks:
  api_net:

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9042
    ports:
      - "9042:9042"
    networks:
      - api_net
    volumes:
      - ~/mongors/data1:/data/db
    depends_on:
      - mongo2
    secrets:
      - RS_USER
      - RS_PASSWORD
    env_file:
      - ../docker/secrets/rs_db_parameters.env
    environment:
      RS_USERNAME_FILE: ../docker/secrets/prod_replicaset_username
      RS_PASSWORD_FILE: ../docker/secrets/prod_replicaset_password
    healthcheck:
      test: mongo --user=$$RS_USERNAME --password=$$RS_PASSWORD --port=9042
      interval: 20s
      timeout: 10s
      start_period: 5s
      retries: 5

  mongo2:
    container_name: mongo2
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9142
    ports:
      - "9142:9142"
    networks:
      - api_net
    volumes:
      - ~/mongors/data2:/data/db
    depends_on:
      - mongo3

  mongo3:
    container_name: mongo3
    image: mongo:4.4.4
    restart: always
    ports:
      - "9242:9242"
    command: mongod --replSet docker-rs --port 9242
    networks:
      - api_net
    volumes:
      - ~/mongors/data3:/data/db

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api_vol:/data/db
    networks:
      - api_net
    depends_on:
      - mongo1
    secrets:
      - RS_USER
      - RS_PASSWORD
    env_file:
      - ../docker/secrets/rs_db_parameters.env
    environment:
      RS_USERNAME_FILE: ../docker/secrets/prod_replicaset_username
      RS_PASSWORD_FILE: ../docker/secrets/prod_replicaset_password
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m