version: "3.4"

x-common-variables:
  &env-vars
  PORT_API: 8080
  HOST_DB: mongo1
  PORT_DB: 27017

networks:
  api-net:

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.4
    restart: always
    ports:
      - "27017:27017"
    networks:
      - api-net
    volumes:
      - ../docker/mongo-data-db-std:/data/db
    environment:
      *env-vars

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../..
      dockerfile: ../Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ../docker/mongo-data-db-std:/data/db
    depends_on:
      - mongo1
    networks:
      - api-net
    env_file:
      - ./envs/env_dev_standalone.env
    environment:
      PORT_DEBUG: 5005
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m